### ---Test the SERVER 
GET http://localhost:8080

### --Test ALL authors
GET http://localhost:8080/authors

### --Test ALL books
GET http://localhost:8080/books

### --Test ALL members
GET http://localhost:8080/members

### --Test SINGLE book
GET http://localhost:8080/books/670d619f2fa7a06fdc54cb35

### ---Render ALL books---
GET https://cse341-project2-1nzc.onrender.com/wzmeta

### ---Render SINGLE book
GET https://cse341-project2-1nzc.onrender.com/wzmeta/67042e0d3ff6863a1b20f07e

### ---Create a book---
POST http://localhost:8080/books HTTP/1.1
Content-Type: application/json

{
    "title": "The Eye of the World",
    "author_id": "670d62302fa7a06fdc54cb36",
    "avgRating": 9.6,
    "numCopies": 5,
    "avaliableCopies": 4
}

### Update a book
PUT http://localhost:8080/books/670d629e2fa7a06fdc54cb38 HTTP/1.1
Content-Type: application/json

{
    "title": "The Eye of the World",
    "author_id": "670d62302fa7a06fdc54cb36",
    "avgRating": 9.6,
    "numCopies": 5,
    "avaliableCopies": 4
}

### Delete a book
DELETE http://localhost:8080/books/670457f1aaef353e292ef441 HTTP/1.1

#### MEMBERS ####

### Get all members
get http://localhost:8080/members

### Get member by ID
get http://localhost:8080/members/670f1606090223fec7f2346d

### Add a new Member
POST http://localhost:8080/members
Content-Type: application/json

{
    "firstName": "TESTfirst",
    "lastName": "TESTlast",
    "email": "email@email.com",
    "dob": "2001-01-01",
    "accountType": "member",
    "loans": [],
    "toBeRead": []
}

### Add a new Member with invalid dob
POST http://localhost:8080/members
Content-Type: application/json

{
    "firstName": "TESTfirst",
    "lastName": "TESTlast",
    "email": "email@email.com",
    "dob": "2001-01-152",
    "accountType": "member",
    "loans": [],
    "toBeRead": []
}

### Add book to TBR
POST http://localhost:8080/members/add
Content-Type: application/json

{
    "memberID": "670d61142fa7a06fdc54cb33",
    "listType": "toBeRead",
    "itemID": "670d629e2fa7a06fdc54cb38"
}

### Remove book to TBR
POST http://localhost:8080/members/remove
Content-Type: application/json

{
    "memberID": "670d61142fa7a06fdc54cb33",
    "listType": "toBeRead",
    "itemID": "670d629e2fa7a06fdc54cb38"
}

### Get all loans
get http://localhost:8080/loans

### Get by loan ID
get http://localhost:8080/loans/67133197d8f9836cac147629

### Get by loan ID
get http://localhost:8080/loans/member/670d61142fa7a06fdc54cb33

### Create loan
post http://localhost:8080/loans/add
Content-Type: application/json

{
    "memberID": "670d61142fa7a06fdc54cb33",
    "bookID": "670d629e2fa7a06fdc54cb38",
    "startDate": "11/01/2024",
    "endDate": "11/07/2024"
}

### Update loan
put http://localhost:8080/loans/update/67137825aae48c98cc79fc70
Content-Type: application/json

{
    "memberID": "670d61142fa7a06fdc54cb33",
    "bookID": "670d629e2fa7a06fdc54cb38",
    "startDate": "10/20/2024",
    "endDate": "11/07/2024"
}

### Remove loan by loan Id
DELETE  http://localhost:8080/loans/remove/67133197d8f9836cac147629 HTTP/1.1
